### PR TITLE
Fixing tests after merge from upstream

### PR DESCRIPTION
**Pull request by justinrsweeney**

### CODE REVIEW

**Review by magibney — APPROVED** [review]
LGTM! Curious, do you know what accounts for the reduced byte count in `testDocCollectionSerializationNoIndent()`?

**Comment by justinrsweeney** [comment]
> LGTM! Curious, do you know what accounts for the reduced byte count in `testDocCollectionSerializationNoIndent()`?

I believe this is due to the removal of some unnecessary fields that were previously added to state and then fixed in this issue: https://issues.apache.org/jira/browse/SOLR-16593

**Comment by magibney** [comment]
Great, thanks! that makes sense. Looks like the precommit failure would be addressed by the formatting changes included in #70 -- I almost wonder if it's worth it to run :solr:core:spotlessApply on this PR (#71) and merge it first -- that way you have all the "mechanical" changes in this PR and it should (ideally) clarify the more substantial (content-wise, if not line-count-wise) change introduced by #70 ...

**Comment by justinrsweeney** [comment]
Makes sense, applying the formatting here which is whitespace only changes on FacetProcessor.

**Comment by magibney** [comment]
> Makes sense, applying the formatting here which is whitespace only changes on FacetProcessor.

Nice! I sanity-checked the diff this PR vs. #70 and it's exactly what one would hope/expect. I think this is good to merge, followed by #70

**Pull request merged**
