### PR TITLE
added solr.install.dir for tests

### PR DESCRIPTION
**Pull request by hiteshk25**
@magibney can you please looks this and see if its ok to set here as this require for plugin tests

### CODE REVIEW

**Comment by magibney** [comment]
Esp. since we're on 9.1 I'm assuming (perhaps incorrectly?) that there must be a "right" way to do this that doesn't involve forking Solr? I'm happy to dig into this, but a little more context would be helpful.

**Comment by hiteshk25** [comment]
While running the plugin test I see following exception. If I set that property then it works
```
org.apache.solr.common.SolrException: solr.install.dir property not initialized

	at __randomizedtesting.SeedInfo.seed([43F62461C26850BF]:0)
	at org.apache.solr.core.NodeConfig.getSolrInstallDir(NodeConfig.java:262)
	at org.apache.solr.core.NodeConfig.setupSharedLib(NodeConfig.java:440)
	at org.apache.solr.core.NodeConfig.<init>(NodeConfig.java:198)
	at org.apache.solr.core.NodeConfig$NodeConfigBuilder.build(NodeConfig.java:788)
	at org.apache.solr.util.TestHarness.buildTestNodeConfig(TestHarness.java:223)
	at org.apache.solr.util.TestHarness.<init>(TestHarness.java:153)
	at org.apache.solr.util.TestHarness.<init>(TestHarness.java:160)
	at org.apache.solr.util.TestHarness.<init>(TestHarness.java:105)
	at org.apache.solr.SolrTestCaseJ4.createCore(SolrTestCaseJ4.java:850)
	at org.apache.solr.SolrTestCaseJ4.initCore(SolrTestCaseJ4.java:837)
	at org.apache.solr.SolrTestCaseJ4.initCore(SolrTestCaseJ4.java:683)
	at mn.fs.solr.funnel.TestDistributedFunnelComponent.beforeTests(TestDistributedFunnelComponent.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:886)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.SystemPropertiesRestoreRule$1.evaluate(SystemPropertiesRestoreRule.java:80)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by magibney** [comment]
Does [this commit](https://github.com/apache/solr/commit/b0eff2ca815) (from upstream `branch_9x` help? Will be included in 9.2 release.

**Comment by hiteshk25** [comment]
> Does [this commit](https://github.com/apache/solr/commit/b0eff2ca815) (from upstream `branch_9x` help? Will be included in 9.2 release.

Thanks. looks like they removed the `exception throwing` part. I will try this later.

**Comment by magibney** [comment]
> looks like they removed the exception throwing part

Right, but iiuc this may actually be the right thing to do? Basically, the `solr.install.dir` is used for examples and stuff by internal solr tests, but it's not integral to the test framework, so for the test framework to be used in 3rd party contexts, it makes no sense to throw an exception.

So the fix you had worked, but based on the conversation on that issue, it looks [any placeholder directory](https://issues.apache.org/jira/browse/SOLR-16553?focusedCommentId=17637701#comment-17637701) would suffice? ... at which point really the issue is behavior in cases where an unset `solr.install.dir` is perfectly fine.

**Comment by hiteshk25** [comment]
> > looks like they removed the exception throwing part
> 
> Right, but iiuc this may actually be the right thing to do? Basically, the `solr.install.dir` is used for examples and stuff by internal solr tests, but it's not integral to the test framework, so for the test framework to be used in 3rd party contexts, it makes no sense to throw an exception.
> 
> So the fix you had worked, but based on the conversation on that issue, it looks [any placeholder directory](https://issues.apache.org/jira/browse/SOLR-16553?focusedCommentId=17637701#comment-17637701) would suffice? ... at which point really the issue is behavior in cases where an unset `solr.install.dir` is perfectly fine.

You mean when to unset the `solr.install.dir` property?  that's why I asked you as I was not sure. I just ran the solr tests and I don't see immediate issue with it.

**Comment by magibney** [comment]
Sorry, I didn't mean that it should ever be necessary to explicitly "unset" the property -- just that when using Solr test-framework outside of the context of the actual Solr test suite (as we do with plugins, and as any plugin developer might reasonably be expected to do) `solr.install.dir` is not used for anything, so it's irrelevant, and if the test-framework throws an exception when it hasn't been set, that pointlessly makes the Solr test-framework unusable in a third-party context (without weird workarounds).

The commit/issue I referenced above I think fixes this by causing `solr.install.dir` to no longer be required (which, effectively, it previously had been).

**Pull request closed without merging**
