### PR TITLE
gradle ide support adjustments

### PR DESCRIPTION
**Pull request by magibney**

### CODE REVIEW

**Comment by magibney** [comment]
I'd like to do a proper merge of this, rather than a squash-merge, unless there are objections.

**Comment by hiteshk25** [comment]
> I'd like to do a proper merge of this, rather than a squash-merge, unless there are objections.

Sure. we need to do cherry pick for fs/branch_9_1?

**Review by hiteshk25 — APPROVED** [review]
LGTM (Thanks @magibney )

**Comment by magibney** [comment]
Done! (as a manual merge commit since this is a special case and merge commits are not normally supported in this repo).

**Comment by magibney** [comment]
> we need to do cherry pick for fs/branch_9_1?

Yes, I'll take care of this. That one can easily be a single/squash commit.

**Pull request merged**
