### PR TITLE
SOLR-16448: Set default indent size to 0 for json serilization

### PR DESCRIPTION
**Pull request by Oldsouldier**
* Changed indent size for state.json file from 2 to 0

* updated test. Set default indent to 0

https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by justinrsweeney** [comment]
Question for this one, since we have compression for state.json in Solr now, do we think this is still worthwhile? I believe compression would do a better job shrinking file size than removing indentation alone.

**Comment by hiteshk25** [comment]
> Question for this one, since we have compression for state.json in Solr now, do we think this is still worthwhile? I believe compression would do a better job shrinking file size than removing indentation alone.

I think it always good to process less data in memory/network.

**Comment by justinrsweeney** [comment]
If we are compressing, then I don't think it'll change it, we might want to run a quick test to see if indentation matters with compression. My thinking is that with compression, this change isn't impactful.

**Comment by hiteshk25** [comment]
> If we are compressing, then I don't think it'll change it, we might want to run a quick test to see if indentation matters with compression. My thinking is that with compression, this change isn't impactful.

I can think of two cost
1. serializing the doccollection object to json. It will generate ~20% more bytes, so we need to process more bytes to compress.
2. While de serializing again we have to process 20% more bytes. (with large collection it is around 200k bytes)

That's the processing time we will save. Also, for small collection we don't want to compress.

But agree, compressible data will have similar number of bytes.

**Comment by Oldsouldier** [comment]
I actually agree with compression being a more general performance solution. 
Regarding potential public upstreaming, just removing indents might provide partial benefit while maintaining online edit-ability, but without a great way to configure this it might be more of an annoyance to the majority of users.

**Comment by hiteshk25** [comment]
> I actually agree with compression being a more general performance solution. Regarding potential public upstreaming, just removing indents might provide partial benefit while maintaining online edit-ability, but without a great way to configure this it might be more of an annoyance to the majority of users.

Edit with compression is another issue to consider.
For indentation, we can always add a system property. Would be good to discuss bit in a solr community?

**Review by hiteshk25 — APPROVED** [review]
LGTM

**Comment by Oldsouldier** [comment]
@hiteshk25 should i close this? Or merge with the test failures?

**Comment by justinrsweeney** [comment]
@Oldsouldier I think we can go ahead and merge this, the failures look to be unrelated.

**Comment by magibney** [comment]
Do we want to cherry-pick/backport this to `fs/branch_9_1` for release?

**Comment by justinrsweeney** [comment]
> Do we want to cherry-pick/backport this to `fs/branch_9_1` for release?

Yup, we should cherry pick this to `fs/branch_9_1`.

**Comment by magibney** [comment]
> Yup, we should cherry pick this to fs/branch_9_1.

👍 ... once that's done I'll do a PR to get this into fs-solr builds. (I'm happy to take care of cherry-picking this too, @Oldsouldier ... lmk what you prefer)

**Pull request merged**
