### PR TITLE
Reset cached results on merge.

### PR DESCRIPTION
**Pull request by claygoddard**
Must reset cached results on merge for refinement.

### CODE REVIEW

**Comment by claygoddard** [comment]
Seems like I also need to merge into this fs/branch_9_3 and then I'll bump in fs-solr

**Review by magibney — APPROVED** [review]
Looks good; and sorry, not sure how this fell through the cracks with the migration to solr 9. Ideally the flow would be to merge this to fs/branch_9x and then backport (cherry-pick) to the release branch (currently fs/branch_9_3). It should be fine practically speaking to merge this as-is and then cherry-pick to fs/branch_9x if you don't want to worry about manipulating this PR (changing the base branch, etc).

We definitely want this on fs/branch_9x though because then it will just automatically be included in future 9x release branches.

**Comment by claygoddard** [comment]
> We definitely want this on fs/branch_9x though because then it will just automatically be included in future 9x release branches.

Sweet, yep already merged into that branch here https://github.com/cowpaths/fullstory-solr/pull/174

**Comment by magibney** [comment]
> Sweet, yep already merged into that branch here https://github.com/cowpaths/fullstory-solr/pull/174

Thanks, not sure how I missed that! This should be good to go then!

**Pull request merged**
