### PR TITLE
SAI-5069:   Expose metrics for various solr operations

### PR DESCRIPTION
**Pull request by noblepaul**

### CODE REVIEW

**Comment by hiteshk25** [comment]
CCIng @magibney

**Review by magibney — COMMENTED** [review]
Do we maybe also want `cumulativeDeletesByQuery`? I don't actually mind leaving that metric out; but if we're leaving it out, what's the logic for what's included/excluded?

**Comment by hiteshk25** [comment]
Looks like we can add following

1. cumulativeAdds
2. cumulativeDeletesById
3. cumulativeDeletesByQuery

Feel free to add for any other solr ops

**Comment by noblepaul** [comment]
all the changes will be merged into #216

**Pull request closed without merging**
