### PR TITLE
sc 214640 : log cleanup and req tracing [from lucene-solr]

### PR DESCRIPTION
**Pull request by patsonluk**
## Description
Apply changes from https://github.com/fullstorydev/lucene-solr/pull/102

## Solution
Apply changes for the above branch, details:

Changes included in this PR:
1. Add log marker based on path (upstreamed in https://issues.apache.org/jira/browse/SOLR-16582)
2. Add info message on search start (not upstreamed, see discussions in https://github.com/apache/solr/pull/1237 https://issues.apache.org/jira/browse/SOLR-16586)
3. Simplified message on sub-shard requests -(not upstreamed as this is quite specific to FS usage. Solr community might not like the fact that full query is no longer printed for handler processing in the data node - for us it's okay as it's easy for us to see ALL logs across nodes including QA node from BQ)
4.  Enable handling of rid from external systems - (not upstreamed, Solr is using the OpenTracing context at [here](https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/servlet/ServletUtils.java#L255) which is in theory more generic. However, for FS, it's easier for us to use rid as our request id generated from alexa/anita does not comply to OpenTracing trace ID format, hence it's easier for us to "workaround" it by using rid which has no format restriction)
5. Adding rid to the [solr/server/resources/log4j2.xml](https://github.com/cowpaths/fullstory-solr/pull/49/files#diff-f950301391ca4cf160f002305de69ca7fc4b02a0b284b67d3b04b0f3291de6ee) , use the %notEmpty{} expression to avoid empty rid tags

Changes skipped in this PR:
1. In SearchHandler, generate/tag rid (request id) earlier and include such in MDC context. Very similar change was already implemented in 9.0 by another contributor https://issues.apache.org/jira/browse/SOLR-15790 .

### CODE REVIEW

**Comment by hiteshk25** [comment]
@patsonluk is it better to create separate PR for each issue?

**Comment by patsonluk** [comment]
@hiteshk25 I have broken it down for upstream PRs (those proposed to apache community).

As for local merges (within fullstory-solr) from our own 8.x to 9.x, can we do a 1-1 mapping for PR? (one PR in 9.X for each PR in 8.x)

**Review by hiteshk25 — APPROVED** [review]
LGTM( just see if you can verify logs!)

**Comment by patsonluk** [comment]
> LGTM( just see if you can verify logs!)

Thanks! Tested locally (by running solr in cloud mode directly, ie `bin/solr -p 9999 -c -a "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=19999"`) to ensure:
1. Marker is working (adding /replication and /get to ignore and issued http://localhost:9999/solr/test/get). Added jira issue to use AsyncLogger to be consistent with usage in 9.x https://fullstory.atlassian.net/browse/SAI-4295
2. Log on start of query such as `Start External Search Query...`
3. Use a autogenerated rid if not provided (`localhost-n`), if provided an `rid` from as query param, then such rid will be used and logged

**Pull request merged**
