### PR TITLE
SAI-5048:   Expose node level histogram for request time in solr/metrics

### PR DESCRIPTION
**Pull request by noblepaul**
Use aggregate metrics wherever possible

### CODE REVIEW

**Comment by noblepaul** [comment]
@hiteshk25 @patsonluk  We only have a subset of metrics exposed in Solr as node level aggregate metrics. Should we go ahead and make it possible to expose the other variables as well ?

**Comment by patsonluk** [comment]
> @hiteshk25 @patsonluk We only have a subset of metrics exposed in Solr as node level aggregate metrics. Should we go ahead and make it possible to expose the other variables as well ?

I recall that it could be useful to have the actual values of `requestTimes` (not just the count) , so we can know the duration (p50, p99) etc for various ops (select/update) for each node.

Do we have a list of other variables that you think are useful? Perhaps you can help to come up with a list so we can go over them?

Many thanks! 😊

**Comment by hiteshk25** [comment]
@noblepaul we need metrics at node level for all the ops as mentioned in ticket.

**Comment by noblepaul** [comment]
sure @hiteshk25 . I'll add them and update the PR

**Comment by patsonluk** [comment]
Closing this as the change was integrated into https://github.com/cowpaths/mn/pull/81026 and was merged

**Pull request closed without merging**
