### PR TITLE
Port over BitDocSet max calculation.

### PR DESCRIPTION
**Pull request by claygoddard**

### CODE REVIEW

**Comment by claygoddard** [comment]
Do I use `fs/branch_9_1` or `fs/branch_9x`? I see PRs for both but the checked in commit for the submodule points at `fs/branch_9_1`.

**Comment by hiteshk25** [comment]
> Do I use `fs/branch_9_1` or `fs/branch_9x`? I see PRs open for both but the checked in commit for the submodule points at `fs/branch_9_1`.

1st `fs/branch_9x` branch then cherry-pick that commit to `fs/branch_9_1`

**Comment by claygoddard** [comment]
> > Do I use `fs/branch_9_1` or `fs/branch_9x`? I see PRs open for both but the checked in commit for the submodule points at `fs/branch_9_1`.
> 
> 1st `fs/branch_9x` branch then cherry-pick that commit to `fs/branch_9_1`

SG. Will do that now. Changing the base messed things up for a moment!

**Comment by claygoddard** [comment]
I'm noticing the build failed due to formatting. Is this something we're intending to enforce here? What should I do about that?

**Comment by hiteshk25** [comment]
> I'm noticing the build failed due to formatting. Is this something we're intending to enforce here? What should I do about that?

we need to run `./gradlew spotlessApply` from solr folder, that should fix this.

**Comment by claygoddard** [comment]
> Edit
> Hide
> Delete

Will do! Just wasn't sure if that was something we were intending to enforce here. Will update in a bit.

**Review by hiteshk25 — APPROVED** [review]
LGTM

**Comment by claygoddard** [comment]
...currently trying to determine if these solr test failures are expected.

**Comment by claygoddard** [comment]
> ...currently trying to determine if these solr test failures are expected.

Other commits have the same failures. So seems like yes.

**Pull request merged**
